<?php

declare(strict_types=1);

namespace DejwCake\YahooFinance\Models\ResponseModels;

use Carbon\CarbonInterface;
use DejwCake\YahooFinance\ApiClient\Models\ResponseModel as ResponseModelInterface;

readonly class StockQuote implements ResponseModelInterface
{
    public function __construct(
        public string $symbol,
        public string $language,
        public string $region,
        public ?string $quoteType,
        public ?string $quoteSourceName,
        public ?bool $triggerable,
        public ?string $currency,
        public ?string $shortName,
        public ?string $marketState,
        public ?string $exchange,
        public ?string $longName,
        public ?string $messageBoardId,
        public ?string $exchangeTimezoneName,
        public ?string $exchangeTimezoneShortName,
        public ?int $gmtOffSetMilliseconds,
        public ?string $market,
        public ?bool $esgPopulated,
        public ?float $epsTrailingTwelveMonths,
        public ?float $epsForward,
        public ?float $epsCurrentYear,
        public ?float $priceEpsCurrentYear,
        public ?int $sharesOutstanding,
        public ?float $bookValue,
        public ?float $fiftyDayAverage,
        public ?float $fiftyDayAverageChange,
        public ?float $fiftyDayAverageChangePercent,
        public ?float $twoHundredDayAverage,
        public ?float $twoHundredDayAverageChange,
        public ?float $twoHundredDayAverageChangePercent,
        public ?int $marketCap,
        public ?float $forwardPE,
        public ?float $priceToBook,
        public ?int $sourceInterval,
        public ?int $exchangeDataDelayedBy,
        public ?string $averageAnalystRating,
        public ?int $firstTradeDateMilliseconds,
        public ?int $priceHint,
        public ?float $regularMarketChange,
        public ?float $regularMarketChangePercent,
        public ?CarbonInterface $regularMarketTime,
        public ?float $regularMarketPrice,
        public ?float $regularMarketDayHigh,
        public ?string $regularMarketDayRange,
        public ?float $regularMarketDayLow,
        public ?int $regularMarketVolume,
        public ?float $regularMarketPreviousClose,
        public ?float $postMarketChangePercent,
        public ?CarbonInterface $postMarketTime,
        public ?float $postMarketPrice,
        public ?float $postMarketChange,
        public ?float $bid,
        public ?float $ask,
        public ?int $bidSize,
        public ?int $askSize,
        public ?string $fullExchangeName,
        public ?string $financialCurrency,
        public ?float $regularMarketOpen,
        public ?int $averageDailyVolume3Month,
        public ?int $averageDailyVolume10Day,
        public ?float $fiftyTwoWeekLowChange,
        public ?float $fiftyTwoWeekLowChangePercent,
        public ?string $fiftyTwoWeekRange,
        public ?float $fiftyTwoWeekHighChange,
        public ?float $fiftyTwoWeekHighChangePercent,
        public ?float $fiftyTwoWeekLow,
        public ?float $fiftyTwoWeekHigh,
        public ?CarbonInterface $dividendDate,
        public ?CarbonInterface $earningsTimestamp,
        public ?CarbonInterface $earningsTimestampStart,
        public ?CarbonInterface $earningsTimestampEnd,
        public ?float $trailingAnnualDividendRate,
        public ?float $trailingPE,
        public ?float $trailingAnnualDividendYield,
        public ?bool $tradeable,
        public ?string $displayName,
    ) {
    }
}
